In [1]:
import numpy as np

In [2]:
# train data
D = 1000
d1 = [1, 1, 1, 0, 0, 0, 0, 0, 0] * D
d2 = [1, 1, 0, 1, 1, 0, 0, 0, 0] * D
d3 = [0, 1, 0, 0, 1, 1, 0, 0, 0] * D
d4 = [0, 1, 0, 0, 0, 0, 1, 1, 1] * D

train_data = np.array([d1, d2, d3, d4] * D)
print(train_data.shape)
label = np.array(['B', 'B', 'C', 'N'] * D)

# test data
d5 = np.array([[1, 0, 0, 1, 0, 0, 0, 1, 0] * D])
d6 = np.array([[0, 1, 0, 0, 0, 0, 0, 1, 1] * D])


(4000, 9000)


In [3]:
import numpy as np
from typing import *
import matplotlib.pyplot as plt
import sys
# caution: path[0] is reserved for script path (or '' in REPL)
sys.path.insert(1, '/home/nghiatnh/Study/Sem5/AIL302m/Projects/AIL302m-Machine_Learning/')
from Modules.classification.naive_bayes import BernoulliNB

In [4]:
MNB = BernoulliNB()
MNB.fit(train_data, label)
print(MNB.predict(train_data))
print(MNB.predict_proba(train_data))
MNB.score(train_data, label)

['B' 'B' 'C' ... 'B' 'C' 'N']
[[1.00000000e+000 1.03221875e-095 1.84223712e-099]
 [1.00000000e+000 4.94643770e-092 4.95473300e-147]
 [9.36877984e-059 1.00000000e+000 1.77252038e-104]
 ...
 [1.00000000e+000 4.94643770e-092 4.95473300e-147]
 [9.36877984e-059 1.00000000e+000 1.77252038e-104]
 [1.94402331e-157 9.87172802e-146 1.00000000e+000]]


1.0

In [5]:
from __future__ import print_function
from sklearn.naive_bayes import BernoulliNB
import numpy as np 

In [6]:
## call MultinomialNB
clf = BernoulliNB()
# training 
clf.fit(train_data, label)

# test
print('Predicting class of d5:', str(clf.predict(train_data)))
print('Probability of d6 in each class:', clf.predict_proba(train_data))

Predicting class of d5: ['B' 'B' 'C' ... 'B' 'C' 'N']
Probability of d6 in each class: [[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
